### PR TITLE
Fix regex to recognize older data as T96

### PR DESCRIPTION
**Pull request by kathy-nevola**
# Title: Adding back support for older data
**Problem:** New version of function expects Target 96, Target 48, or flex format to be in panel name. Older data only contained Olink in panel name + an extra "|" was added in Flex regex causing all old files to be read as Flex data and would convert LOD and missing freq to samples. 

**Solution:** Extra pipe was removed from Flex regex and additional if statement was added to capture older data panel formats and recognize them as T96.

**Key Features:**

* Older data where panel is "Olink xxxxx" is now recognized as T96 data not flex
* New data still works  (all tests pass)

## Checklist
- [x] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [x] Make sure you are make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [ ] Add or update unit tests (if applicable)
- [x] Check your code with any unit tests (Run devtools::check() locally)
- [x] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Documentation Update 
- [ ] Other (explain)

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, any questions you have, etc...

Consider linking any issues (#issue-number ) or adding @mentions to ensure specific people see it.

### CODE REVIEW

**Review by amrita-kar — CHANGES_REQUESTED** [review]
I keep getting this error message on parsing the new script below with old Target 96 data :

```
library(tidyverse)
library(OlinkAnalyze)
source("Read_NPX_data.R")
data <- read_NPX("T96_NPX.xlsx")
```

Error 
image

Do I need to add the print and capture function also?

**Comment by kathy-nevola** [comment]
did you install this version of Olink Analyze over the cran version of Olink Analyze?

**Comment by amrita-kar** [comment]
Yes I used the OA version on the OA-476_oldnpx branch. This works
image

Working code
image

I think the issue is fixed?

**Comment by kathy-nevola** [comment]
ok sounds good

**Comment by kathy-nevola** [comment]
Functions as expected with devtools load_all
````
devtools::load_all()
data <- read_NPX("Old_Data.xlsx")
# Target 96 data in wide form detected.
# Warning message:
#   In check_data_completeness(out) :
#   The following samples have NA NPX values for the following panels.
is.na(nrow(data)) # False
is.na(ncol(data)) # False
all(data$MissingFreq == 0) # FALSE - missing frequency is not just set to 0
any(data$SampleID == "LOD") # FALSE - no samples called LOD

```

**Review by amrita-kar — APPROVED** [review]

**Pull request merged**
