### PR TITLE
New data support

### PR DESCRIPTION
**Pull request by kathy-nevola**
# Title: Edits to read_NPX to support additional Olink data file format types
**Problem:** Currently long target data and data with additional column names arent supported

**Solution:** Created a new if statement in read_target_data where if G2 (Panel Name) contains Target, then the data is assumed to be in long format and is read in directly and formated/checked as in wide format data. Additionally new Explore columns in version 3 were added.

**Key Features:**

* Can read in long format Target 96 and Target 48 data
* Target 48 is removed from panel names
* New column names (sample_type, ExploreVersion) are explicitly supported

I checked this function with some data that Jes sent. 

## Checklist
- [x] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [x] Make sure you are make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [ ] Add or update unit tests (if applicable)
- [x] Check your code with any unit tests (Run devtools::check() locally)
- [ ] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Documentation Update 
- [ ] Other (explain)

## Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, any questions you have, etc...

Consider linking any issues (#issue-number ) or adding @mentions to ensure specific people see it.

### CODE REVIEW

**Comment by amrita-kar** [comment]
Pull Request Reviewing Process #PR 211
1. Check the PR is going to the right branch (main or develop) – **develop correct**

2. Write down a list of expectations for the problem

- Expectation 1: read long format for Target 96 and Target 48 data Read_NPX_data.R

- [ ] Display above data in long format - **Yes reads Target 96 and 48 in long format**

- Expectation 2: Target 48 removed from panel names

- [ ] Error for Target 48 in panel name - _Couldn't find the test data to check this_

- Expectation 2: New column names added sample_type and ExploreVersion

- [ ] Error if above columns not found. However, works with the above columns missing. Should it be so? My test code is below
```
# has Sample_Type and ExploreVersion  and from the data posted on DataScience --> General Teams chat 
data <- read_NPX("../../RShiny_testdata-main/New_extNPX_Data.csv") %>% 
dplyr::select(-SampleID, -Panel_Lot_Nr, -Sample_Type, -ExploreVersion) %>%
write_csv("../../RShiny_testdata-main/New_NPX_Data_removed.csv")
data_removed <- read_NPX("../../RShiny_testdata-main/New_NPX_Data_removed.csv")

Error in read_NPX_explore(filename = filename) : Cannot find columns: SampleID,Panel_Lot_Nr 
## my comment : only throws error for SampleID and Panel_Lot_Nr and not for Sample_Type and ExploreVersion
```
Preprocessing
• read_NPX_data.R - Display Target 96 and Target 48 data in long format, error in Target 48 in panel name and check on additional 2 columns 
 
3. Run the test data for each part each expectation and run tests – Data created by Jes and Kathy/Pascal and modified by Amrita
 A) Check data from Jes (Teams message Kathy)
 B) Check on test files for Pascal (Datascience --> General [New explore NPX files is the header])

**Review by amrita-kar — APPROVED** [review]

**Comment by kathy-nevola** [comment]
To test expectation 2, read in Target 48 data and check that data frame does not have Target 48 present in the data frame. 
For expectation 3, this behaves as expected, since it will default to the explore version that doesnt have Sample_type and ExploreVersion. Maybe instead testing that Sample_Type is required if ExploreVersion is present but not Sample_type and ExploreVersion is required when Sample_Type is present and not ExploreVersion.

Otherwise the review looks great! Thanks!

**Comment by amrita-kar** [comment]
For expectation2 I am doing the following
`data_target48_quant <- read_NPX("../../RShiny_testdata-main/RShiny_testdata-main/Test Data2/Target 48_QUANT_LONG.xlsx") `.... and I see Target 48 in the dataframe
image

**Comment by kathy-nevola** [comment]
Yes that is perfect. Thanks!

**Comment by amrita-kar** [comment]
My final comment in that case Kathy for expectation3 

```
data <- read_NPX("../../RShiny_testdata-main/New_extNPX_Data.csv") %>% # has Sample_Type and ExploreVersion  
  dplyr::select(-Sample_Type) %>% # removing Sample_Type with ExploreVersion
  write_csv("../../RShiny_testdata-main/New_NPX_Data_removed.csv")

# _this still reads the data when Sample_Type is missing and ExploreVersion is present which it shouldn't?_
data_removed <- read_NPX("../../RShiny_testdata-main/New_NPX_Data_removed.csv") 
```
Feel free to add your test.

**Comment by amrita-kar** [comment]
```
data <- read_NPX("../../RShiny_testdata-main/New_extNPX_Data.csv") %>% # has Sample_Type and ExploreVersion
  dplyr::select(-Sample_Type,-ExploreVersion) %>% # removing Sample_Type with ExploreVersion
  write_csv("../../RShiny_testdata-main/New_NPX_Data_removed.csv")

data_removed <- read_NPX("../../RShiny_testdata-main/New_NPX_Data_removed.csv") # works when ExploreVersion and Sample_Type both missing
```
```
data <- read_NPX("../../RShiny_testdata-main/New_extNPX_Data.csv") %>% # has Sample_Type and ExploreVersion
  dplyr::select(-Sample_Type,-ExploreVersion) %>% # removing Sample_Type only 
  write_csv("../../RShiny_testdata-main/New_NPX_Data_removed.csv")

data_removed <- read_NPX("../../RShiny_testdata-main/New_NPX_Data_removed.csv") # doesn't work as mentioned in the `expectation3`

Error in read_NPX_explore(filename = filename) :
  Cannot find columns: Sample_Type
```
So seems like all the parameters in this review are good to go and can be merged!

**Pull request merged**
