### PR TITLE
Matrix CI fix to main

### PR DESCRIPTION
**Pull request by klevdiamanti**
# Title: Install Matrix from source
**Problem:** CI was failing due to an update in the R package Matrix.

**Solution:** We forced Matrix to install from source in CI so that it works.

## Checklist
- [ ] Make sure you are requesting to **pull a feature/bugfix branch** (right side). This should not be main or develop.
- [X] Make sure you make a pull request against either **main or develop** (left side). (Requesting to main should be reserved for bugfixes and new releases)
- [ ] Add or update unit tests (if applicable)
- [ ] Check your code with any unit tests (Run devtools::check() locally)
- [ ] Add neccessary documentation (if applicable)

## Type of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue) (link the issue on the right)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code style update (formatting, renaming)
- [ ] Documentation Update 
- [ ] Other (explain)

### CODE REVIEW

**Review by kathy-nevola — APPROVED** [review]
LGTM, I think its good to merge pending CI devel success

**Comment by kathy-nevola** [comment]
All good, feel free to merge

**Comment by klevdiamanti** [comment]
> All good, feel free to merge

@kathy-nevola please take another look and we can merge.

**Review by kathy-nevola — APPROVED** [review]
Looks great! Thanks.

**Pull request merged**
